### ISSUE TITLE
Should include localization density maps in outputs

### ISSUE THREAD

**Issue by benmwebb** [integrativemodeling/nup84#2]
@Pellarin @procyon777 The localization density maps (as in Fig. 6 in the paper) would be extremely useful for anybody that wants to use the Nup84 model (rather than having them overinterpret a single cluster representative). But I don't see these in the repository anywhere. Do we have them? If so, where are they?

**Comment by benmwebb** [comment]
@Pellarin @procyon777 If you can point me to the location where these files are on our storage, I can tidy things up and add them to the repository.

**Comment by Pellarin** [comment]
Sorry, overlooked your previous message. I've shared the densities with you through dropbox. They're in the old .dx format, maybe they should be converted in a modern .mrc one?

**Comment by benmwebb** [comment]
Got them, thanks! I'll add them to the repository. `.dx` format should be fine. I'd rather preserve what we did than risk losing data in a conversion.
